// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package fizzbuzzpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FizzBuzzServiceClient is the client API for FizzBuzzService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FizzBuzzServiceClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
}

type fizzBuzzServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFizzBuzzServiceClient(cc grpc.ClientConnInterface) FizzBuzzServiceClient {
	return &fizzBuzzServiceClient{cc}
}

func (c *fizzBuzzServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/proto.v1.fizzbuzzpb.FizzBuzzService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fizzBuzzServiceClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, "/proto.v1.fizzbuzzpb.FizzBuzzService/Stats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FizzBuzzServiceServer is the server API for FizzBuzzService service.
// All implementations must embed UnimplementedFizzBuzzServiceServer
// for forward compatibility
type FizzBuzzServiceServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	mustEmbedUnimplementedFizzBuzzServiceServer()
}

// UnimplementedFizzBuzzServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFizzBuzzServiceServer struct {
}

func (UnimplementedFizzBuzzServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedFizzBuzzServiceServer) Stats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedFizzBuzzServiceServer) mustEmbedUnimplementedFizzBuzzServiceServer() {}

// UnsafeFizzBuzzServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FizzBuzzServiceServer will
// result in compilation errors.
type UnsafeFizzBuzzServiceServer interface {
	mustEmbedUnimplementedFizzBuzzServiceServer()
}

func RegisterFizzBuzzServiceServer(s grpc.ServiceRegistrar, srv FizzBuzzServiceServer) {
	s.RegisterService(&FizzBuzzService_ServiceDesc, srv)
}

func _FizzBuzzService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FizzBuzzServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.v1.fizzbuzzpb.FizzBuzzService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FizzBuzzServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FizzBuzzService_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FizzBuzzServiceServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.v1.fizzbuzzpb.FizzBuzzService/Stats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FizzBuzzServiceServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FizzBuzzService_ServiceDesc is the grpc.ServiceDesc for FizzBuzzService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FizzBuzzService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.v1.fizzbuzzpb.FizzBuzzService",
	HandlerType: (*FizzBuzzServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _FizzBuzzService_Get_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _FizzBuzzService_Stats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/fizzbuzzpb/fizzbuzz.proto",
}
